/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type BridgingFeeFromTokens = ContractEventLog<{
  gas: string;
  0: string;
}>;
export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;
export type ReceiveFee = ContractEventLog<{
  bridgeTransactionCost: string;
  messageTransactionCost: string;
  0: string;
  1: string;
}>;
export type Received = ContractEventLog<{
  0: string;
  1: string;
}>;
export type Swapped = ContractEventLog<{
  sender: string;
  recipient: string;
  sendToken: string;
  receiveToken: string;
  sendAmount: string;
  receiveAmount: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
  5: string;
}>;
export type TokensReceived = ContractEventLog<{
  amount: string;
  recipient: string;
  nonce: string;
  messenger: string;
  message: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
}>;
export type TokensSent = ContractEventLog<{
  amount: string;
  recipient: string;
  destinationChainId: string;
  receiveToken: string;
  nonce: string;
  messenger: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
  5: string;
}>;

export interface Bridge extends BaseContract {
  constructor(jsonInterface: any[], address?: string, options?: ContractOptions): Bridge;
  clone(): Bridge;
  methods: {
    accumulatedFee(arg0: string): NonPayableTransactionObject<string>;

    addBridgeToken(chainId_: number | string | BN, tokenAddress_: string | number[]): NonPayableTransactionObject<void>;

    addPool(pool: string, token: string | number[]): NonPayableTransactionObject<void>;

    allbridgeMessenger(): NonPayableTransactionObject<string>;

    canSwap(): NonPayableTransactionObject<string>;

    chainId(): NonPayableTransactionObject<string>;

    gasUsage(arg0: number | string | BN): NonPayableTransactionObject<string>;

    getBridgingCostInTokens(
      destinationChainId: number | string | BN,
      messenger: number | string | BN,
      tokenAddress: string
    ): NonPayableTransactionObject<string>;

    getMessageCost(chainId: number | string | BN, protocol: number | string | BN): NonPayableTransactionObject<string>;

    getTransactionCost(chainId_: number | string | BN): NonPayableTransactionObject<string>;

    hasReceivedMessage(
      message: string | number[],
      protocol: number | string | BN
    ): NonPayableTransactionObject<boolean>;

    hasSentMessage(message: string | number[]): NonPayableTransactionObject<boolean>;

    hashMessage(
      amount: number | string | BN,
      recipient: string | number[],
      sourceChainId: number | string | BN,
      destinationChainId: number | string | BN,
      receiveToken: string | number[],
      nonce: number | string | BN,
      messenger: number | string | BN
    ): NonPayableTransactionObject<string>;

    otherBridgeTokens(arg0: number | string | BN, arg1: string | number[]): NonPayableTransactionObject<boolean>;

    otherBridges(arg0: number | string | BN): NonPayableTransactionObject<string>;

    owner(): NonPayableTransactionObject<string>;

    pools(arg0: string | number[]): NonPayableTransactionObject<string>;

    processedMessages(arg0: string | number[]): NonPayableTransactionObject<string>;

    rebalancer(): NonPayableTransactionObject<string>;

    receiveTokens(
      amount: number | string | BN,
      recipient: string | number[],
      sourceChainId: number | string | BN,
      receiveToken: string | number[],
      nonce: number | string | BN,
      messenger: number | string | BN,
      receiveAmountMin: number | string | BN
    ): PayableTransactionObject<void>;

    registerBridge(
      chainId_: number | string | BN,
      bridgeAddress_: string | number[]
    ): NonPayableTransactionObject<void>;

    removeBridgeToken(
      chainId_: number | string | BN,
      tokenAddress_: string | number[]
    ): NonPayableTransactionObject<void>;

    renounceOwnership(): NonPayableTransactionObject<void>;

    sentMessages(arg0: string | number[]): NonPayableTransactionObject<string>;

    setAllbridgeMessenger(_allbridgeMessenger: string): NonPayableTransactionObject<void>;

    setCanSwap(_canDeposit: boolean): NonPayableTransactionObject<void>;

    setGasOracle(gasOracle_: string): NonPayableTransactionObject<void>;

    setGasUsage(chainId_: number | string | BN, gasUsage_: number | string | BN): NonPayableTransactionObject<void>;

    setRebalancer(_rebalancer: string): NonPayableTransactionObject<void>;

    setWormholeMessenger(_wormholeMessenger: string): NonPayableTransactionObject<void>;

    swap(
      amount: number | string | BN,
      token: string | number[],
      receiveToken: string | number[],
      recipient: string,
      receiveAmountMin: number | string | BN
    ): NonPayableTransactionObject<void>;

    swapAndBridge(
      token: string | number[],
      amount: number | string | BN,
      recipient: string | number[],
      destinationChainId: number | string | BN,
      receiveToken: string | number[],
      nonce: number | string | BN,
      messenger: number | string | BN,
      feeTokenAmount: number | string | BN
    ): PayableTransactionObject<void>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

    withdrawBridgingFeeInTokens(token: string): NonPayableTransactionObject<void>;

    withdrawGasTokens(amount: number | string | BN): NonPayableTransactionObject<void>;

    wormholeMessenger(): NonPayableTransactionObject<string>;
  };
  events: {
    BridgingFeeFromTokens(cb?: Callback<BridgingFeeFromTokens>): EventEmitter;
    BridgingFeeFromTokens(options?: EventOptions, cb?: Callback<BridgingFeeFromTokens>): EventEmitter;

    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(options?: EventOptions, cb?: Callback<OwnershipTransferred>): EventEmitter;

    ReceiveFee(cb?: Callback<ReceiveFee>): EventEmitter;
    ReceiveFee(options?: EventOptions, cb?: Callback<ReceiveFee>): EventEmitter;

    Received(cb?: Callback<Received>): EventEmitter;
    Received(options?: EventOptions, cb?: Callback<Received>): EventEmitter;

    Swapped(cb?: Callback<Swapped>): EventEmitter;
    Swapped(options?: EventOptions, cb?: Callback<Swapped>): EventEmitter;

    TokensReceived(cb?: Callback<TokensReceived>): EventEmitter;
    TokensReceived(options?: EventOptions, cb?: Callback<TokensReceived>): EventEmitter;

    TokensSent(cb?: Callback<TokensSent>): EventEmitter;
    TokensSent(options?: EventOptions, cb?: Callback<TokensSent>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "BridgingFeeFromTokens", cb: Callback<BridgingFeeFromTokens>): void;
  once(event: "BridgingFeeFromTokens", options: EventOptions, cb: Callback<BridgingFeeFromTokens>): void;

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(event: "OwnershipTransferred", options: EventOptions, cb: Callback<OwnershipTransferred>): void;

  once(event: "ReceiveFee", cb: Callback<ReceiveFee>): void;
  once(event: "ReceiveFee", options: EventOptions, cb: Callback<ReceiveFee>): void;

  once(event: "Received", cb: Callback<Received>): void;
  once(event: "Received", options: EventOptions, cb: Callback<Received>): void;

  once(event: "Swapped", cb: Callback<Swapped>): void;
  once(event: "Swapped", options: EventOptions, cb: Callback<Swapped>): void;

  once(event: "TokensReceived", cb: Callback<TokensReceived>): void;
  once(event: "TokensReceived", options: EventOptions, cb: Callback<TokensReceived>): void;

  once(event: "TokensSent", cb: Callback<TokensSent>): void;
  once(event: "TokensSent", options: EventOptions, cb: Callback<TokensSent>): void;
}
